# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-18 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classcast_karma_history',
            fields=[
                ('Serial_Number', models.IntegerField(primary_key=True, serialize=False)),
                ('student_id', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('karma_points', models.FloatField()),
            ],
            options={
                'db_table': 'classcast_karma_history',
            },
        ),
    ]
